title: "FPRO Notebooks"
logo: images/feup-logo.png
execute:
  execute_notebooks: "auto"
repository:
  url: https://github.com/fpro-feup/notebooks
html:
  use_repository_button: true
exclude_patterns: [venv/*, images/*]